# https://developers.home-assistant.io/docs/add-ons/configuration
name: "CouchDB"
version: "1.1.1"
slug: "couchdb"
description: "A database that embraces the web, running as a HA add-on, for obsidian-livesync"
url: "https://github.com/geekinsideme/ha-couchdb-addon"
arch:
  - aarch64
  - armv7
init: false
startup: "services"
boot: "auto"
map:
  - "data:rw"
  - "local.ini:/opt/couchdb/etc/local.ini:ro"
ports:
  "5984/tcp": 5984
ports_description:
  "5984/tcp": "CouchDB Web UI (Fauxton) and HTTP API"
webui: "http://[HOST]:[PORT:5984]/_utils/"
options:
  couchdb_user: "admin"
  couchdb_password: ""
schema:
  couchdb_user: "str"
  couchdb_password: "password"